# Generated by Django 3.2.5 on 2021-07-21 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_card_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
