# Generated by Django 3.2.5 on 2021-07-22 12:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_auto_20210722_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='flashcards.profile'),
            preserve_default=False,
        ),
    ]
