# Generated by Django 3.2.5 on 2021-07-22 15:48

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0006_alter_card_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='card',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null='true', verbose_name='image'),
            preserve_default='true',
        ),
    ]
